// engine/premium.js — the underdog premium (prompts 58/68, GO ruling
// 2026-07-31): harder challenge, more reward. When a map measurably
// disadvantages one team, that team's Recognition earns a 25% premium
// — disclosed, sweep-derived, never hand-tuned.
//
// THE TABLE IS GENERATED, not authored: `node tools/gen_premium.mjs
// <normal.csv> <mirror.csv> <profile>` reads a mirrored battery pair
// and convicts only a TEAM-linked lean past the threshold (an
// aggregate the fairness doctrine would also convict). As of
// 2026-07-31 every live map measures INSIDE the band (frontier 52.9%,
// blackwood 49.4%, riverline 49.6% aggregate A), so the table is
// EMPTY and the mechanism is dormant — which is the honest state: a
// premium that exists without a measured lean is a lie about the map.
//
// Integer math only: 25% premium = points * 5 / 4, floored.

export const PREMIUM_THRESHOLD_PCT = 55; // aggregate lean that convicts
export const PREMIUM_NUM = 5;
export const PREMIUM_DEN = 4;

// profile -> the DISADVANTAGED team (0 or 1). Absent = fair = no premium.
export const MAP_PREMIUM = Object.freeze({
  // First conviction (2026-07-31): sawtooth 69.0% A at n=1200 live
  // config, team-linked, identical pre/post walls — the unique pair on
  // waterless choke terrain. Team B (Outliers) earns the premium while
  // the map is HELD and the mechanism hunt runs. Generated by
  // tools/gen_premium.mjs from map_sawtooth_uq(+_mirror).csv.
  sawtooth: 1,
  // Q69 ACCEPTED (prompt 145): riverline's unique-pair lean — 56.9%
  // A aggregate at n=600 (54.5/59.3, team-linked; uniques-off reads
  // 40.9%). The pair IS the mechanism (seat economics' sibling on the
  // water map); the owner accepted the lean with the premium as
  // disclosure. Generated by gen_premium from map_riverline_uq pair.
  riverline: 1,
});

// D+C ruling (prompt 154): MEASURED TICKET OFFSETS — the outcome-side
// sibling of the premium. On a map where the battery convicts the
// unique pair beyond the band, the DISADVANTAGED team starts with +N
// tickets. GENERATED like the premium (battery ladder tunes N until
// the map reads in band), DISCLOSED in the briefing, and retired
// map-by-map as real mechanism fixes land. rules.handicap === false
// disables (HANDICAP=0); rules.handicapTickets overrides N (the
// ladder's knob).
// profile -> { team: the team that RECEIVES the offset, tickets: N }.
// Seeds below are FIRST GUESSES pending the ladder verdict.
export const MAP_TICKET_OFFSET = Object.freeze({
  // TABLE EMPTY (2026-08-03) — twice-learned law: an offset is
  // "measured" ONLY against a SAME-BUILD baseline pair. Sawtooth:
  // offsets INERT (h20-60 moved ~1 pt). Riverline: the ladder was
  // read against a stale (pre-escort-wall) baseline — the current
  // build's mirror control reads 41.0% A with NO offset (the map's
  // own lean moved). A fresh same-build h0 pair decides whether any
  // offset (and which DIRECTION) is warranted. The mechanism stays,
  // battle-tested and disclosed, awaiting honest numbers.
});

export function ticketOffsetFor(mapProfile, rules) {
  if (rules?.handicap === false) return null;
  const entry = MAP_TICKET_OFFSET[mapProfile];
  if (!entry) return null;
  const n = rules?.handicapTickets ?? entry.tickets;
  return n > 0 ? { team: entry.team, tickets: n } : null;
}

export function premiumPoints(points, team, mapProfile) {
  if (MAP_PREMIUM[mapProfile] === team) {
    return ((points * PREMIUM_NUM) / PREMIUM_DEN) | 0;
  }
  return points;
}
