// client/js/strings.js — Slice 15B part 1: the string table. Every
// high-frequency user-facing string flows through t(key, params); locale
// switches live (⚙ panel) and persists in localStorage. Catalogs must
// stay key-identical across locales — a test enforces parity.
// Part 2 (follow-up): describeEvent's parameterized feed lines.

export const CATALOGS = {
  en: {
    // ── rejections (key = "rej." + engine reason, verbatim) ──
    "rej.operator already active": "That command seat is taken.",
    "rej.operator not active": "Join the war first.",
    "rej.no such asset": "No such asset.",
    "rej.asset belongs to other team": "That asset fights for the enemy.",
    "rej.asset already operated": "A teammate is driving that one.",
    "rej.no asset selected": "Take an asset first (click one or press Next asset).",
    "rej.asset not operable": "Your asset is out of action.",
    "rej.no such target": "No such target.",
    "rej.friendly target": "Hold fire — that one is ours.",
    "rej.target not operable": "Target is already a wreck.",
    "rej.reloading": "Weapon reloading.",
    "rej.out of ammo": "Out of ammo — resupply at base.",
    "rej.out of supply": "Out of supply — hold a relay or fall back.",
    "rej.target out of range": "Target out of range.",
    "rej.target not spotted": "No spotter on that target.",
    "rej.no line of sight": "No line of sight.",
    "rej.no such wreck": "Nothing to tow there.",
    "rej.not a wreck": "That unit doesn't need a tow.",
    "rej.enemy wreck": "We don't tow enemy scrap.",
    "rej.already under tow": "Someone already has that wreck in tow.",
    "rej.already recovering": "That wreck is already in the repair bay.",
    "rej.already towing": "You're already towing a wreck.",
    "rej.wreck out of reach": "Get adjacent to the wreck to hook it up.",
    "rej.needs a logistics truck": "Only a logistics truck can tow — switch to one.",
    "rej.not downed": "You are not on foot.",
    "rej.too far to crawl": "Too far — downed operators can only crawl a short way.",
    "rej.still recovering nerve": "Hold on — redeploy unlocks a few seconds after going down.",
    "rej.cannot deploy mines": "Only an assault tank carries mines.",
    "rej.no mines left": "Mine rack empty.",
    "rej.mine already here": "A mine already sits on this ground.",
    "rej.cannot mine a base zone": "Base zones are protected — no mining here.",
    "rej.cannot mine a site": "Sites are protected — no mining here.",
    "rej.cannot clear mines": "Only a logistics truck can clear mines.",
    "rej.no such mine": "No mine there.",
    "rej.too far to clear": "Get adjacent to the mine to clear it.",
    "rej.mine not marked": "Unknown minefield — a scout must mark it first.",
    "rej.unknown ping kind": "That signal is not in the book.",
    "rej.ping cooling down": "Signal lamp recharging — a moment.",
    "rej.only rescue pings while down": "On foot you can only call for rescue.",
    "rej.ping needs a target cell": "Pick a spot on the map to signal about.",
    "rej.takeover needs confirmation":
      "That asset carries real responsibility — press ENTER to confirm the takeover, ESC to cancel.",
    "rej.not a carrier": "That is not a rescue carrier.",
    "rej.no bunk free": "Both bunks are taken.",
    "rej.carrier out of reach": "Crawl next to the carrier to board.",
    "rej.not aboard": "You are not aboard a carrier.",
    "rej.unknown option": "No such setting.",
    "rej.invalid value": "That setting takes on or off.",
    "rej.invalid throttle": "Bad drive input.",
    "rej.invalid turn": "Bad drive input.",
    "rej.no such site": "No such site.",
    "rej.cannot breach sites": "Only artillery can breach infrastructure.",
    "rej.site already damaged": "That site is already in ruins.",
    "rej.no such drone": "That drone is already gone.",
    "rej.cannot track aircraft": "Artillery cannot track aircraft — use a direct gun.",
    "rej.cannot deploy here": "This chassis has no hardpoint to deploy.",
    "rej.already deployed": "Hardpoint already active.",
    "rej.not deployed": "Nothing to stow — you are mobile.",
    "rej.still transitioning": "Hardpoint legs are working — hold.",
    "rej.deployed — undeploy to move": "Sentinel cannot move while deployed.",
    "ev.hardpoint_deploying": "Deploying hardpoint…",
    "ev.hardpoint_active": "Hardpoint active.",
    "ev.hardpoint_undeploying": "Undeploying.",
    "ev.hardpoint_stowed": "Hardpoint stowed — mobile.",
    "banner.deploy": "DEPLOY HARDPOINT (H)",
    "banner.undeploy": "UNDEPLOY (H)",
    "label.deploying": "DEPLOYING {s}s",
    "label.undeploying": "UNDEPLOYING {s}s",
    "label.hardpoint": "HARDPOINT ACTIVE",
    "rej.cargo out of reach": "Pull alongside to transfer cargo.",
    "rej.cargo hold empty": "Cargo hold empty — reload at base.",
    "rej.target is topped up": "They are already topped up.",
    "ev.cargo_transferred": "Truck {by} resupplied asset {id} (+{fuel} fuel, +{ammo} ammo).",
    "banner.resupply": "RESUPPLY ASSET {id} (V)",
    "ui.cargo": "Cargo {fuel}f/{ammo}a",
    "rej.rate limited": "Slow down — command flood throttled.",
    "rej.spectators only watch": "Spectators only watch.",
    "rej.war is over": "The war is over — next one starts shortly.",
    "rej.fallback": "Order rejected: {reason}",
    // ── event feed lines (15B part 2) ──
    "ev.operator_unboarded": "Operator {id} hopped off.",
    "ev.site_shelled": "Relay {id} under artillery fire!",
    "ev.site_damaged": "Relay {id} is DOWN — a truck with materiel can rebuild it.",
    "ev.site_repaired": "Relay {id} rebuilt and humming.",
    "ev.site_neutralized_us": "Relay {id} neutralized — hold to capture!",
    "ev.site_neutralized_them": "Relay {id} is being taken — defend it!",
    "ev.site_captured_us": "Relay {id} secured.",
    "ev.site_captured_them": "Relay {id} lost to the enemy!",
    "ev.asset_disabled": "Asset {id} disabled.",
    "ev.mine_deployed": "Mine laid ({n} left in the rack).",
    "ev.mine_marked": "Scouts marked an enemy mine.",
    "ev.mine_detonated": "MINE! Asset {id} hit.",
    "ev.mine_cleared": "Mine cleared by asset {id}.",
    "ev.ping": "[PING] {label} @ ({x},{y})",
    "ev.drone_launched": "DRONE UP — someone idled too long off supply. Move or shoot it down.",
    "ev.drone_hit": "Drone stinging asset {id} — move!",
    "ev.drone_downed": "Drone downed by asset {id}.",
    "ev.drone_recalled": "The drone broke off.",
    "ev.resupplied": "Asset {id} resupplied.",
    "ev.standard_taken_us": "WE HAVE THEIR STANDARD! Escort it home!",
    "ev.standard_taken_them": "THEY TOOK OUR STANDARD! Stop the carrier!",
    "ev.standard_dropped": "The standard is down — race for it!",
    "ev.standard_returned_us": "Our standard is safe at base.",
    "ev.standard_returned_them": "Enemy standard recovered to their base.",
    "ev.standard_scored_us": "STANDARD CAPTURED — VICTORY!",
    "ev.standard_scored_them": "Enemy scored our standard.",
    "ev.operator_downed": "Operator {id} is DOWN — crawl to cover, redeploy, or await a carrier.",
    "ev.operator_rescued": "Carrier {by} picked up operator {id}!",
    "ev.operator_delivered": "Operator {id} delivered safe — take a new asset.",
    "ev.operator_redeployed": "Operator {id} redeployed — take a new asset.",
    "ev.operator_returned": "Operator {id} made it back on foot.",
    "ev.tow_started": "Asset {by} is towing wreck {id}.",
    "ev.recovery_started": "Wreck {id} in the repair bay.",
    "ev.asset_restored": "Asset {id} restored to duty!",
    "ev.asset_manufactured": "Home base rebuilt asset {id} — reinforcements!",
    // ── end screen ──
    "end.victory": "VICTORY",
    "end.defeat": "DEFEAT",
    "end.draw": "DRAW",
    "end.next_war": "Next war begins in ~{s}s — stay in your seat.",
    "end.honors": "HONORS",
    "win.interrupted": "war interrupted",
    "win.elimination": "enemy force eliminated",
    "win.domination": "all relays dominated",
    "win.points": "time limit — points decide",
    "win.standard": "Command Standard captured",
    "win.unknown": "unknown",
    // ── briefing ──
    "brief.fight_for": "You fight for {name}.",
    "brief.win": "WIN: a COMMAND CARRIER must take the enemy standard (tall banner) home while your own standard is safe. Trucks tow wrecks; everyone escorts.",
    "brief.relays": "RELAYS (masts on the road) project supply — out of supply you crawl and cannot fire.",
    "brief.fog": "Enemies are hidden by fog until your units get close. Wrecks can be towed home and repaired.",
    "brief.clicks": "Click: your unit = take it · ground = move · enemy = fire · friendly wreck = tow.",
    // ── ping options ──
    "ping.attack": "ATTACK HERE",
    "ping.defend": "DEFEND HERE",
    "ping.rally": "RALLY ON ME",
    "ping.need_escort": "NEED ESCORT",
    "ping.escort_standard": "ESCORT THE STANDARD",
    "ping.carrier_under_attack": "CARRIER UNDER ATTACK",
    "ping.recovery_in_progress": "RECOVERY IN PROGRESS",
    "ping.road_blocked": "ROAD BLOCKED",
    "ping.mines_detected": "MINES DETECTED",
    "ping.safe_route": "SAFE ROUTE MARKED",
    "ping.need_rescue": "NEED RESCUE",
    "ping.need_supplies": "NEED SUPPLIES",
    "status.no_fuel": "OUT OF FUEL — a truck can refuel you (V beside you)",
    "status.low_fuel": "Fuel low ({n})",
    "status.no_ammo": "OUT OF AMMO — resupply at base or from a truck",
    "status.low_ammo": "Ammo low ({n})",
    "status.no_supply": "OUT OF SUPPLY — no firing; hold a relay or fall back",
    "status.reloading": "Reloading {s}s",
    "status.suppressed": "Suppressed {s}s — sensors degraded",
    "status.deploying": "Deploying {s}s",
    "status.undeploying": "Undeploying {s}s",
    "status.deployed": "HARDPOINT ACTIVE — undeploy to move",
    "status.request": "REQUEST SUPPLIES",
    "hover.vacant": "{name} — vacant · click to take",
    "hover.stats": "ⓘ stats",
    "codex.traits": "Traits",
    "toast.mission": "MISSION COMPLETE  +{n} pts",
    "board.title": "TEAM TOP 5",
    "ui.center_me": "⌖ center on me",
    "page.title": "FIRELINE COMMAND",
    "page.tagline": "Join the battle. Turn the front.",
    "page.pitch": "An active war is running. Pick a side and take command of an asset. Click ground to move, click a visible enemy to fire. Return to base to resupply.",
    "page.join_a": "Join THE DIRECTORATE (west) — fortify · contain · stabilize",
    "page.join_b": "Join THE OUTLIERS (east) — bypass · improvise · disrupt",
    "page.spectate": "Spectate (watch the whole war)",
    "page.fallback2d": "2D sprite view — WebGL unavailable; spectating only",
    "page.replays": "Replay viewer (archived wars)",
    "page.move_out": "Move out (Enter)",
    "page.next_asset": "Next asset",
    "page.center": "Center",
    "page.hints": "WASD/arrows pan · wheel zoom · F follow · Home base · X standard · R redeploy · M mine / C clear · 1/2/3 pings · B board / U unboard / T tow / V cargo · G direct drive · H hardpoint · click: select/fire/tow/move",
    "enc.title": "FIELD ENCYCLOPEDIA",
    "enc.units": "Units",
    "enc.mechanics": "How the war works",
    "enc.standard": "THE COMMAND STANDARD — the primary objective. Only a Command Carrier can take the enemy's standard; carry it home while YOUR standard is safe at base and the war is won. Dropped standards auto-return after 60 s.",
    "enc.supply": "SUPPLY — bases and owned relays project supply (20/12 cells). Out of supply you move at half speed and cannot fire. Idle in your base to refuel and rearm; logistics trucks carry field resupply.",
    "enc.rescue": "RESCUE — crews bail out of destroyed vehicles and walk. Redeploy after 10 s (R), crawl to cover, or wait for a Command Carrier to pick you up. Trucks tow wrecks home for repair at half hull. Rescue scores HIGHER than kills.",
    "enc.mines": "MINES — assault tanks lay up to 2 (M). They arm in 3 s and detonate on enemy contact (60 damage). Your team always sees its own; enemy scouts MARK them for their team; trucks clear marked mines (C).",
    "enc.drone": "THE DRONE — idle outside your supply umbrella for 30 s and the enemy's nearest relay launches one. It stings until you MOVE. Any direct gun downs it in one shot — click it.",
    "enc.sites": "RELAYS — stand alone on a relay to flip it (3 s to neutralize, 3 s to raise). Contested flags freeze. Artillery can SHELL relays into ruins; a truck carrying materiel rebuilds them.",
    "enc.factions": "FACTIONS — The Directorate (fortify · contain · stabilize; unique: the deployable Sentinel) versus The Outliers (bypass · improvise · disrupt; unique: the amphibious Skimmer). Neither side is the good guys.",
    // ── mission cards ──
    "task.stop_thief": "STOP THE THIEF — our standard is moving",
    "task.secure_standard": "Secure our standard — it lies in the open",
    "task.escort_carrier": "Escort the standard run home",
    "task.rescue": "Rescue operator {id} — a carrier can pick them up",
    "task.defend_relay": "Defend relay {id} — the flag is dropping",
    "task.repair_site": "Rebuild relay {id} — a truck with materiel can fix it",
    "task.recover": "Recover asset {id} — tow it home",
    "task.towing_now": "Towing asset {id} — head home",
    // ── banners & world labels ──
    "banner.down_wait": "YOU ARE DOWN — redeploy in {s}s",
    "banner.down_ready": "REDEPLOY NOW (R) — or crawl to a carrier",
    "banner.tow": "TOW ASSET {id} (T)",
    "label.you_down": "YOU ARE DOWN — R TO REDEPLOY",
    "label.board_here": "CARRIER HERE — B TO BOARD",
    "label.operator_down": "OPERATOR DOWN",
    "label.repairing": "REPAIRING {s}s",
    "label.relay": "RELAY — {who}",
    "label.relay_damaged": "DAMAGED — truck + materiel rebuilds",
    "label.relay_raising": "RAISING {s}s",
    "label.relay_dropping": "DROPPING {s}s — DEFEND!",
    "label.who_yours": "YOURS",
    "label.who_enemy": "ENEMY",
    "label.who_neutral": "NEUTRAL",
    "label.std_yours": "YOUR STANDARD",
    "label.std_enemy": "ENEMY STANDARD — STEAL IT",
    "label.std_yours_down": "YOUR STANDARD IS DOWN",
    "label.std_enemy_open": "ENEMY STANDARD IN THE OPEN",
    "label.std_returns": "auto-returns in {s}s",
    "ui.direct_on": "DIRECT DRIVE — W/S throttle, A/D steer, G to exit",
    "ui.direct_off": "Direct drive off — click-to-move restored.",
    "ui.spectating": "Spectating — you see everything, you touch nothing.",
    "ui.new_war": "A new war has begun!",
    "ui.crewing": "You are crewing asset {id} — click ground to move",
  },
  no: {
    "rej.operator already active": "Den kommandoplassen er opptatt.",
    "rej.operator not active": "Bli med i krigen først.",
    "rej.no such asset": "Ingen slik enhet.",
    "rej.asset belongs to other team": "Den enheten kjemper for fienden.",
    "rej.asset already operated": "En lagkamerat kjører den.",
    "rej.no asset selected": "Ta en enhet først (klikk en, eller trykk Neste enhet).",
    "rej.asset not operable": "Enheten din er ute av drift.",
    "rej.no such target": "Ingen slikt mål.",
    "rej.friendly target": "Ikke skyt — den er vår.",
    "rej.target not operable": "Målet er allerede et vrak.",
    "rej.reloading": "Våpenet lades om.",
    "rej.out of ammo": "Tom for ammunisjon — etterforsyn i basen.",
    "rej.out of supply": "Uten forsyning — hold et relé eller trekk tilbake.",
    "rej.target out of range": "Målet er utenfor rekkevidde.",
    "rej.target not spotted": "Ingen observatør på målet.",
    "rej.no line of sight": "Ingen siktelinje.",
    "rej.no such wreck": "Ingenting å taue der.",
    "rej.not a wreck": "Den enheten trenger ikke tauing.",
    "rej.enemy wreck": "Vi tauer ikke fiendens skrap.",
    "rej.already under tow": "Noen tauer allerede det vraket.",
    "rej.already recovering": "Vraket er allerede i verkstedet.",
    "rej.already towing": "Du tauer allerede et vrak.",
    "rej.wreck out of reach": "Still deg inntil vraket for å koble på.",
    "rej.needs a logistics truck": "Bare en lastebil kan taue — bytt til en.",
    "rej.not downed": "Du er ikke til fots.",
    "rej.too far to crawl": "For langt — nedkjempede operatører kryper bare korte strekk.",
    "rej.still recovering nerve": "Vent litt — redeploy låses opp noen sekunder etter at du gikk ned.",
    "rej.cannot deploy mines": "Bare en stridsvogn bærer miner.",
    "rej.no mines left": "Minestativet er tomt.",
    "rej.mine already here": "Det ligger alt en mine her.",
    "rej.cannot mine a base zone": "Basesoner er fredet — ingen minelegging her.",
    "rej.cannot mine a site": "Anlegg er fredet — ingen minelegging her.",
    "rej.cannot clear mines": "Bare en lastebil kan rydde miner.",
    "rej.no such mine": "Ingen mine der.",
    "rej.too far to clear": "Still deg inntil minen for å rydde den.",
    "rej.mine not marked": "Ukjent minefelt — en speider må merke det først.",
    "rej.unknown ping kind": "Det signalet finnes ikke i boka.",
    "rej.ping cooling down": "Signallampen lader — et øyeblikk.",
    "rej.only rescue pings while down": "Til fots kan du bare rope om redning.",
    "rej.ping needs a target cell": "Velg et sted på kartet å signalisere om.",
    "rej.takeover needs confirmation":
      "Den enheten bærer et stort ansvar — trykk ENTER for å bekrefte, ESC for å avbryte.",
    "rej.not a carrier": "Det er ikke en redningsvogn.",
    "rej.no bunk free": "Begge køyene er opptatt.",
    "rej.carrier out of reach": "Kryp inntil vognen for å gå om bord.",
    "rej.not aboard": "Du er ikke om bord i noen vogn.",
    "rej.unknown option": "Ingen slik innstilling.",
    "rej.invalid value": "Innstillingen tar på eller av.",
    "rej.invalid throttle": "Ugyldig kjøreinput.",
    "rej.invalid turn": "Ugyldig kjøreinput.",
    "rej.no such site": "Ingen slikt anlegg.",
    "rej.cannot breach sites": "Bare artilleri kan knuse infrastruktur.",
    "rej.site already damaged": "Anlegget ligger alt i ruiner.",
    "rej.no such drone": "Den dronen er alt borte.",
    "rej.cannot track aircraft": "Artilleri kan ikke følge luftmål — bruk en direkteskytende kanon.",
    "rej.cannot deploy here": "Denne vognen har ingen utplasserbar stilling.",
    "rej.already deployed": "Stillingen er alt aktiv.",
    "rej.not deployed": "Ingenting å pakke sammen — du er mobil.",
    "rej.still transitioning": "Beina jobber — vent.",
    "rej.deployed — undeploy to move": "Sentinel kan ikke flytte mens den er utplassert.",
    "ev.hardpoint_deploying": "Utplasserer stilling…",
    "ev.hardpoint_active": "Stillingen er aktiv.",
    "ev.hardpoint_undeploying": "Pakker sammen.",
    "ev.hardpoint_stowed": "Stillingen er pakket — mobil.",
    "banner.deploy": "UTPLASSER STILLING (H)",
    "banner.undeploy": "PAKK SAMMEN (H)",
    "label.deploying": "UTPLASSERER {s}s",
    "label.undeploying": "PAKKER {s}s",
    "label.hardpoint": "STILLING AKTIV",
    "rej.cargo out of reach": "Legg deg inntil for å overføre last.",
    "rej.cargo hold empty": "Lasterommet er tomt — fyll opp i basen.",
    "rej.target is topped up": "De er allerede fylt opp.",
    "ev.cargo_transferred": "Lastebil {by} etterforsynte enhet {id} (+{fuel} drivstoff, +{ammo} ammo).",
    "banner.resupply": "ETTERFORSYN ENHET {id} (V)",
    "ui.cargo": "Last {fuel}d/{ammo}a",
    "rej.rate limited": "Ro ned — kommandoflommen struptes.",
    "rej.spectators only watch": "Tilskuere bare ser på.",
    "rej.war is over": "Krigen er over — neste starter straks.",
    "rej.fallback": "Ordre avvist: {reason}",
    "ev.operator_unboarded": "Operatør {id} hoppet av.",
    "ev.site_shelled": "Relé {id} under artilleriild!",
    "ev.site_damaged": "Relé {id} er NEDE — en lastebil med materiell kan gjenoppbygge det.",
    "ev.site_repaired": "Relé {id} gjenoppbygd og i drift.",
    "ev.site_neutralized_us": "Relé {id} nøytralisert — hold stand for å ta det!",
    "ev.site_neutralized_them": "Relé {id} er i ferd med å bli tatt — forsvar det!",
    "ev.site_captured_us": "Relé {id} sikret.",
    "ev.site_captured_them": "Relé {id} tapt til fienden!",
    "ev.asset_disabled": "Enhet {id} slått ut.",
    "ev.mine_deployed": "Mine lagt ({n} igjen i stativet).",
    "ev.mine_marked": "Speiderne merket en fiendtlig mine.",
    "ev.mine_detonated": "MINE! Enhet {id} truffet.",
    "ev.mine_cleared": "Mine ryddet av enhet {id}.",
    "ev.ping": "[PING] {label} @ ({x},{y})",
    "ev.drone_launched": "DRONE I LUFTA — noen sto for lenge uten forsyning. Flytt deg eller skyt den ned.",
    "ev.drone_hit": "Dronen stikker enhet {id} — flytt deg!",
    "ev.drone_downed": "Drone skutt ned av enhet {id}.",
    "ev.drone_recalled": "Dronen brøt av.",
    "ev.resupplied": "Enhet {id} etterforsynt.",
    "ev.standard_taken_us": "VI HAR STANDARTEN DERES! Eskorter den hjem!",
    "ev.standard_taken_them": "DE TOK STANDARTEN VÅR! Stopp vognen!",
    "ev.standard_dropped": "Standarten ligger nede — kappløp om den!",
    "ev.standard_returned_us": "Standarten vår er trygg i basen.",
    "ev.standard_returned_them": "Fiendens standart berget hjem til dem.",
    "ev.standard_scored_us": "STANDART EROBRET — SEIER!",
    "ev.standard_scored_them": "Fienden vant med standarten vår.",
    "ev.operator_downed": "Operatør {id} er NEDE — kryp i dekning, redeploy, eller vent på en vogn.",
    "ev.operator_rescued": "Vogn {by} plukket opp operatør {id}!",
    "ev.operator_delivered": "Operatør {id} levert trygt — ta en ny enhet.",
    "ev.operator_redeployed": "Operatør {id} tilbake i tjeneste — ta en ny enhet.",
    "ev.operator_returned": "Operatør {id} kom seg hjem til fots.",
    "ev.tow_started": "Enhet {by} tauer vrak {id}.",
    "ev.recovery_started": "Vrak {id} i verkstedet.",
    "ev.asset_restored": "Enhet {id} tilbake i tjeneste!",
    "ev.asset_manufactured": "Hjemmebasen bygde om enhet {id} — forsterkninger!",
    "end.victory": "SEIER",
    "end.defeat": "NEDERLAG",
    "end.draw": "UAVGJORT",
    "end.next_war": "Neste krig begynner om ~{s}s — bli i setet.",
    "end.honors": "UTMERKELSER",
    "win.interrupted": "krigen ble avbrutt",
    "win.elimination": "fiendens styrke utslettet",
    "win.domination": "alle reléer dominert",
    "win.points": "tidsfrist — poengene avgjør",
    "win.standard": "kommandostandarten erobret",
    "win.unknown": "ukjent",
    "brief.fight_for": "Du kjemper for {name}.",
    "brief.win": "SEIER: en KOMMANDOVOGN må ta fiendens standart (høy fane) hjem mens din egen standart er trygg. Lastebiler tauer vrak; alle eskorterer.",
    "brief.relays": "RELÉER (master langs veien) gir forsyning — uten forsyning kryper du og kan ikke skyte.",
    "brief.fog": "Fiender skjules av tåke til enhetene dine kommer nær. Vrak kan taues hjem og repareres.",
    "brief.clicks": "Klikk: din enhet = ta den · bakken = kjør · fiende = skyt · eget vrak = tau.",
    "ping.attack": "ANGRIP HER",
    "ping.defend": "FORSVAR HER",
    "ping.rally": "SAMLING PÅ MEG",
    "ping.need_escort": "TRENGER ESKORTE",
    "ping.escort_standard": "ESKORTER STANDARTEN",
    "ping.carrier_under_attack": "VOGNEN ER UNDER ANGREP",
    "ping.recovery_in_progress": "BERGING PÅGÅR",
    "ping.road_blocked": "VEIEN ER SPERRET",
    "ping.mines_detected": "MINER OPPDAGET",
    "ping.safe_route": "TRYGG RUTE MERKET",
    "ping.need_rescue": "TRENGER REDNING",
    "ping.need_supplies": "TRENGER FORSYNINGER",
    "status.no_fuel": "TOM FOR DRIVSTOFF — en lastebil kan fylle deg (V ved siden av)",
    "status.low_fuel": "Lite drivstoff ({n})",
    "status.no_ammo": "TOM FOR AMMO — etterforsyn i basen eller fra en lastebil",
    "status.low_ammo": "Lite ammo ({n})",
    "status.no_supply": "UTEN FORSYNING — kan ikke skyte; hold et relé eller trekk tilbake",
    "status.reloading": "Lader om {s}s",
    "status.suppressed": "Undertrykt {s}s — sensorer svekket",
    "status.deploying": "Utplasserer {s}s",
    "status.undeploying": "Pakker {s}s",
    "status.deployed": "STILLING AKTIV — pakk sammen for å flytte",
    "status.request": "BE OM FORSYNINGER",
    "hover.vacant": "{name} — ledig · klikk for å ta",
    "hover.stats": "ⓘ fakta",
    "codex.traits": "Egenskaper",
    "toast.mission": "OPPDRAG FULLFØRT  +{n} pts",
    "board.title": "LAGETS TOPP 5",
    "ui.center_me": "⌖ sentrer på meg",
    "page.title": "FIRELINE COMMAND",
    "page.tagline": "Bli med i slaget. Snu fronten.",
    "page.pitch": "En krig pågår. Velg side og ta kommandoen over en enhet. Klikk på bakken for å kjøre, klikk en synlig fiende for å skyte. Tilbake til basen for etterforsyning.",
    "page.join_a": "Bli med i DIREKTORATET (vest) — befest · innehold · stabiliser",
    "page.join_b": "Bli med i OUTLIERS (øst) — omgå · improviser · forstyrr",
    "page.spectate": "Tilskuer (se hele krigen)",
    "page.fallback2d": "2D-spritevisning — WebGL utilgjengelig; kun tilskuer",
    "page.replays": "Reprisevisning (arkiverte kriger)",
    "page.move_out": "Rykk ut (Enter)",
    "page.next_asset": "Neste enhet",
    "page.center": "Sentrer",
    "page.hints": "WASD/piler panorer · hjul zoomer · F følg · Home base · X standart · R redeploy · M mine / C rydd · 1/2/3 ping · B om bord / U av / T tau / V last · G direkte kjøring · H stilling · klikk: velg/skyt/tau/kjør",
    "enc.title": "FELTLEKSIKON",
    "enc.units": "Enheter",
    "enc.mechanics": "Slik virker krigen",
    "enc.standard": "KOMMANDOSTANDARTEN — hovedmålet. Bare en kommandovogn kan ta fiendens standart; kjør den hjem mens DIN standart står trygt i basen, og krigen er vunnet. Mistede standarter returnerer selv etter 60 s.",
    "enc.supply": "FORSYNING — baser og egne reléer gir forsyning (20/12 ruter). Uten forsyning kjører du halv fart og kan ikke skyte. Stå i basen for å fylle drivstoff og ammo; lastebiler frakter feltforsyning.",
    "enc.rescue": "REDNING — mannskap hopper ut av ødelagte kjøretøy og går til fots. Redeploy etter 10 s (R), kryp i dekning, eller vent på en kommandovogn. Lastebiler tauer vrak hjem til reparasjon. Redning gir MER poeng enn drap.",
    "enc.mines": "MINER — stridsvogner legger inntil 2 (M). De armeres på 3 s og detonerer ved fiendekontakt (60 skade). Laget ditt ser alltid sine egne; fiendens speidere MERKER dem; lastebiler rydder merkede miner (C).",
    "enc.drone": "DRONEN — står du 30 s uten forsyning, letter en drone fra fiendens nærmeste relé. Den stikker til du FLYTTER deg. Én direkteskytende kanon feller den — klikk på den.",
    "enc.sites": "RELÉER — stå alene på et relé for å ta det (3 s å nøytralisere, 3 s å heise). Omstridte flagg fryser. Artilleri kan SKYTE reléer i ruiner; en lastebil med materiell gjenoppbygger dem.",
    "enc.factions": "FRAKSJONENE — Direktoratet (befest · innehold · stabiliser; unik: den utplasserbare Sentinel) mot Outliers (omgå · improviser · forstyrr; unik: den amfibiske Skimmer). Ingen av sidene er de snille.",
    "task.stop_thief": "STOPP TYVEN — standarten vår er på vandring",
    "task.secure_standard": "Sikre standarten vår — den ligger åpent",
    "task.escort_carrier": "Eskorter standartløpet hjem",
    "task.rescue": "Redd operatør {id} — en vogn kan plukke dem opp",
    "task.defend_relay": "Forsvar relé {id} — flagget er på vei ned",
    "task.repair_site": "Gjenoppbygg relé {id} — en lastebil med materiell fikser det",
    "task.recover": "Berg enhet {id} — tau den hjem",
    "task.towing_now": "Tauer enhet {id} — kjør hjem",
    "banner.down_wait": "DU ER NEDE — redeploy om {s}s",
    "banner.down_ready": "REDEPLOY NÅ (R) — eller kryp til en vogn",
    "banner.tow": "TAU ENHET {id} (T)",
    "label.you_down": "DU ER NEDE — R FOR REDEPLOY",
    "label.board_here": "VOGN HER — B FOR Å GÅ OM BORD",
    "label.operator_down": "OPERATØR NEDE",
    "label.repairing": "REPARERER {s}s",
    "label.relay": "RELÉ — {who}",
    "label.relay_damaged": "SKADET — lastebil + materiell gjenoppbygger",
    "label.relay_raising": "HEISES {s}s",
    "label.relay_dropping": "SENKES {s}s — FORSVAR!",
    "label.who_yours": "DERES",
    "label.who_enemy": "FIENDENS",
    "label.who_neutral": "NØYTRALT",
    "label.std_yours": "DIN STANDART",
    "label.std_enemy": "FIENDENS STANDART — STJEL DEN",
    "label.std_yours_down": "STANDARTEN DIN ER NEDE",
    "label.std_enemy_open": "FIENDENS STANDART LIGGER ÅPENT",
    "label.std_returns": "returnerer selv om {s}s",
    "ui.direct_on": "DIREKTE KJØRING — W/S gass, A/D sving, G avslutter",
    "ui.direct_off": "Direkte kjøring av — klikk-og-kjør tilbake.",
    "ui.spectating": "Tilskuer — du ser alt, du rører ingenting.",
    "ui.new_war": "En ny krig har begynt!",
    "ui.crewing": "Du bemanner enhet {id} — klikk på bakken for å kjøre",
  },
};

let LOCALE = "en";

export function setLocale(locale) {
  if (CATALOGS[locale]) LOCALE = locale;
  return LOCALE;
}

export function getLocale() {
  return LOCALE;
}

export function hasKey(key) {
  return key in CATALOGS.en;
}

export function t(key, params = null) {
  const text = CATALOGS[LOCALE][key] ?? CATALOGS.en[key] ?? key;
  if (!params) return text;
  return text.replace(/\{(\w+)\}/g, (m, k) => (k in params ? String(params[k]) : m));
}
