// client/js/strings.js — Slice 15B part 1: the string table. Every
// high-frequency user-facing string flows through t(key, params); locale
// switches live (⚙ panel) and persists in localStorage. Catalogs must
// stay key-identical across locales — a test enforces parity.
// Part 2 (follow-up): describeEvent's parameterized feed lines.

export const CATALOGS = {
  en: {
    // ── rejections (key = "rej." + engine reason, verbatim) ──
    "rej.operator already active": "That command seat is taken.",
    "rej.operator not active": "Join the war first.",
    "rej.no such asset": "No such asset.",
    "rej.asset belongs to other team": "That asset fights for the enemy.",
    "rej.asset already operated": "A teammate is driving that one.",
    "rej.no asset selected": "Take an asset first (click one or press Next asset).",
    "rej.asset not operable": "Your asset is out of action.",
    "rej.no such target": "No such target.",
    "rej.friendly target": "Hold fire — that one is ours.",
    "rej.target not operable": "Target is already a wreck.",
    "rej.reloading": "Weapon reloading.",
    "rej.out of ammo": "Out of ammo — resupply at base.",
    "rej.out of supply": "Out of supply — hold a relay or fall back.",
    "rej.target out of range": "Target out of range.",
    "rej.target not spotted": "No spotter on that target.",
    "rej.no line of sight": "No line of sight.",
    "rej.no such wreck": "Nothing to tow there.",
    "rej.not a wreck": "That unit doesn't need a tow.",
    "rej.enemy wreck": "We don't tow enemy scrap.",
    "rej.already under tow": "Someone already has that wreck in tow.",
    "rej.already recovering": "That wreck is already in the repair bay.",
    "rej.already towing": "You're already towing a wreck.",
    "rej.wreck out of reach": "Get adjacent to the wreck to hook it up.",
    "rej.needs a logistics truck": "Only a logistics truck can tow — switch to one.",
    "rej.not downed": "You are not on foot.",
    "rej.too far to crawl": "Too far — downed operators can only crawl a short way.",
    "rej.still recovering nerve": "Hold on — redeploy unlocks a few seconds after going down.",
    "rej.cannot deploy mines": "Only an assault tank carries mines.",
    "rej.no mines left": "Mine rack empty.",
    "rej.mine already here": "A mine already sits on this ground.",
    "rej.cannot mine a base zone": "Base zones are protected — no mining here.",
    "rej.cannot mine a site": "Sites are protected — no mining here.",
    "rej.cannot clear mines": "Only a logistics truck can clear mines.",
    "rej.no such mine": "No mine there.",
    "rej.too far to clear": "Get adjacent to the mine to clear it.",
    "rej.mine not marked": "Unknown minefield — a scout must mark it first.",
    "rej.unknown ping kind": "That signal is not in the book.",
    "rej.ping cooling down": "Signal lamp recharging — a moment.",
    "rej.only rescue pings while down": "On foot you can only call for rescue.",
    "rej.ping needs a target cell": "Pick a spot on the map to signal about.",
    "rej.takeover needs confirmation":
      "That asset carries real responsibility — press ENTER to confirm the takeover, ESC to cancel.",
    "rej.not a carrier": "That is not a rescue carrier.",
    "rej.no bunk free": "Both bunks are taken.",
    "rej.carrier out of reach": "Crawl next to the carrier to board.",
    "rej.not aboard": "You are not aboard a carrier.",
    "rej.unknown option": "No such setting.",
    "rej.invalid value": "That setting takes on or off.",
    "rej.invalid throttle": "Bad drive input.",
    "rej.invalid turn": "Bad drive input.",
    "rej.no such site": "No such site.",
    "rej.cannot breach sites": "Only artillery can breach infrastructure.",
    "rej.site already damaged": "That site is already in ruins.",
    "rej.no such drone": "That drone is already gone.",
    "rej.cannot track aircraft": "Artillery cannot track aircraft — use a direct gun.",
    "rej.cannot deploy here": "This chassis has no hardpoint to deploy.",
    "rej.already deployed": "Hardpoint already active.",
    "rej.not deployed": "Nothing to stow — you are mobile.",
    "rej.still transitioning": "Hardpoint legs are working — hold.",
    "rej.deployed — undeploy to move": "Sentinel cannot move while deployed.",
    "ev.hardpoint_deploying": "Deploying hardpoint…",
    "ev.hardpoint_active": "Hardpoint active.",
    "ev.hardpoint_undeploying": "Undeploying.",
    "ev.hardpoint_stowed": "Hardpoint stowed — mobile.",
    "banner.deploy": "DEPLOY HARDPOINT (H)",
    "banner.undeploy": "UNDEPLOY (H)",
    "label.deploying": "DEPLOYING {s}s",
    "label.undeploying": "UNDEPLOYING {s}s",
    "label.hardpoint": "HARDPOINT ACTIVE",
    "rej.rate limited": "Slow down — command flood throttled.",
    "rej.spectators only watch": "Spectators only watch.",
    "rej.war is over": "The war is over — next one starts shortly.",
    "rej.fallback": "Order rejected: {reason}",
    // ── ping options ──
    "ping.attack": "ATTACK HERE",
    "ping.defend": "DEFEND HERE",
    "ping.rally": "RALLY ON ME",
    "ping.need_escort": "NEED ESCORT",
    "ping.escort_standard": "ESCORT THE STANDARD",
    "ping.carrier_under_attack": "CARRIER UNDER ATTACK",
    "ping.recovery_in_progress": "RECOVERY IN PROGRESS",
    "ping.road_blocked": "ROAD BLOCKED",
    "ping.mines_detected": "MINES DETECTED",
    "ping.safe_route": "SAFE ROUTE MARKED",
    "ping.need_rescue": "NEED RESCUE",
    // ── mission cards ──
    "task.stop_thief": "STOP THE THIEF — our standard is moving",
    "task.secure_standard": "Secure our standard — it lies in the open",
    "task.escort_carrier": "Escort the standard run home",
    "task.rescue": "Rescue operator {id} — a carrier can pick them up",
    "task.defend_relay": "Defend relay {id} — the flag is dropping",
    "task.repair_site": "Rebuild relay {id} — a truck with materiel can fix it",
    "task.recover": "Recover asset {id} — tow it home",
    "task.towing_now": "Towing asset {id} — head home",
    // ── banners & world labels ──
    "banner.down_wait": "YOU ARE DOWN — redeploy in {s}s",
    "banner.down_ready": "REDEPLOY NOW (R) — or crawl to a carrier",
    "banner.tow": "TOW ASSET {id} (T)",
    "label.you_down": "YOU ARE DOWN — R TO REDEPLOY",
    "label.board_here": "CARRIER HERE — B TO BOARD",
    "label.operator_down": "OPERATOR DOWN",
    "label.repairing": "REPAIRING {s}s",
    "label.relay": "RELAY — {who}",
    "label.relay_damaged": "DAMAGED — truck + materiel rebuilds",
    "label.relay_raising": "RAISING {s}s",
    "label.relay_dropping": "DROPPING {s}s — DEFEND!",
    "label.who_yours": "YOURS",
    "label.who_enemy": "ENEMY",
    "label.who_neutral": "NEUTRAL",
    "label.std_yours": "YOUR STANDARD",
    "label.std_enemy": "ENEMY STANDARD — STEAL IT",
    "label.std_yours_down": "YOUR STANDARD IS DOWN",
    "label.std_enemy_open": "ENEMY STANDARD IN THE OPEN",
    "label.std_returns": "auto-returns in {s}s",
    "ui.direct_on": "DIRECT DRIVE — W/S throttle, A/D steer, G to exit",
    "ui.direct_off": "Direct drive off — click-to-move restored.",
    "ui.spectating": "Spectating — you see everything, you touch nothing.",
    "ui.new_war": "A new war has begun!",
    "ui.crewing": "You are crewing asset {id} — click ground to move",
  },
  no: {
    "rej.operator already active": "Den kommandoplassen er opptatt.",
    "rej.operator not active": "Bli med i krigen først.",
    "rej.no such asset": "Ingen slik enhet.",
    "rej.asset belongs to other team": "Den enheten kjemper for fienden.",
    "rej.asset already operated": "En lagkamerat kjører den.",
    "rej.no asset selected": "Ta en enhet først (klikk en, eller trykk Neste enhet).",
    "rej.asset not operable": "Enheten din er ute av drift.",
    "rej.no such target": "Ingen slikt mål.",
    "rej.friendly target": "Ikke skyt — den er vår.",
    "rej.target not operable": "Målet er allerede et vrak.",
    "rej.reloading": "Våpenet lades om.",
    "rej.out of ammo": "Tom for ammunisjon — etterforsyn i basen.",
    "rej.out of supply": "Uten forsyning — hold et relé eller trekk tilbake.",
    "rej.target out of range": "Målet er utenfor rekkevidde.",
    "rej.target not spotted": "Ingen observatør på målet.",
    "rej.no line of sight": "Ingen siktelinje.",
    "rej.no such wreck": "Ingenting å taue der.",
    "rej.not a wreck": "Den enheten trenger ikke tauing.",
    "rej.enemy wreck": "Vi tauer ikke fiendens skrap.",
    "rej.already under tow": "Noen tauer allerede det vraket.",
    "rej.already recovering": "Vraket er allerede i verkstedet.",
    "rej.already towing": "Du tauer allerede et vrak.",
    "rej.wreck out of reach": "Still deg inntil vraket for å koble på.",
    "rej.needs a logistics truck": "Bare en lastebil kan taue — bytt til en.",
    "rej.not downed": "Du er ikke til fots.",
    "rej.too far to crawl": "For langt — nedkjempede operatører kryper bare korte strekk.",
    "rej.still recovering nerve": "Vent litt — redeploy låses opp noen sekunder etter at du gikk ned.",
    "rej.cannot deploy mines": "Bare en stridsvogn bærer miner.",
    "rej.no mines left": "Minestativet er tomt.",
    "rej.mine already here": "Det ligger alt en mine her.",
    "rej.cannot mine a base zone": "Basesoner er fredet — ingen minelegging her.",
    "rej.cannot mine a site": "Anlegg er fredet — ingen minelegging her.",
    "rej.cannot clear mines": "Bare en lastebil kan rydde miner.",
    "rej.no such mine": "Ingen mine der.",
    "rej.too far to clear": "Still deg inntil minen for å rydde den.",
    "rej.mine not marked": "Ukjent minefelt — en speider må merke det først.",
    "rej.unknown ping kind": "Det signalet finnes ikke i boka.",
    "rej.ping cooling down": "Signallampen lader — et øyeblikk.",
    "rej.only rescue pings while down": "Til fots kan du bare rope om redning.",
    "rej.ping needs a target cell": "Velg et sted på kartet å signalisere om.",
    "rej.takeover needs confirmation":
      "Den enheten bærer et stort ansvar — trykk ENTER for å bekrefte, ESC for å avbryte.",
    "rej.not a carrier": "Det er ikke en redningsvogn.",
    "rej.no bunk free": "Begge køyene er opptatt.",
    "rej.carrier out of reach": "Kryp inntil vognen for å gå om bord.",
    "rej.not aboard": "Du er ikke om bord i noen vogn.",
    "rej.unknown option": "Ingen slik innstilling.",
    "rej.invalid value": "Innstillingen tar på eller av.",
    "rej.invalid throttle": "Ugyldig kjøreinput.",
    "rej.invalid turn": "Ugyldig kjøreinput.",
    "rej.no such site": "Ingen slikt anlegg.",
    "rej.cannot breach sites": "Bare artilleri kan knuse infrastruktur.",
    "rej.site already damaged": "Anlegget ligger alt i ruiner.",
    "rej.no such drone": "Den dronen er alt borte.",
    "rej.cannot track aircraft": "Artilleri kan ikke følge luftmål — bruk en direkteskytende kanon.",
    "rej.cannot deploy here": "Denne vognen har ingen utplasserbar stilling.",
    "rej.already deployed": "Stillingen er alt aktiv.",
    "rej.not deployed": "Ingenting å pakke sammen — du er mobil.",
    "rej.still transitioning": "Beina jobber — vent.",
    "rej.deployed — undeploy to move": "Sentinel kan ikke flytte mens den er utplassert.",
    "ev.hardpoint_deploying": "Utplasserer stilling…",
    "ev.hardpoint_active": "Stillingen er aktiv.",
    "ev.hardpoint_undeploying": "Pakker sammen.",
    "ev.hardpoint_stowed": "Stillingen er pakket — mobil.",
    "banner.deploy": "UTPLASSER STILLING (H)",
    "banner.undeploy": "PAKK SAMMEN (H)",
    "label.deploying": "UTPLASSERER {s}s",
    "label.undeploying": "PAKKER {s}s",
    "label.hardpoint": "STILLING AKTIV",
    "rej.rate limited": "Ro ned — kommandoflommen struptes.",
    "rej.spectators only watch": "Tilskuere bare ser på.",
    "rej.war is over": "Krigen er over — neste starter straks.",
    "rej.fallback": "Ordre avvist: {reason}",
    "ping.attack": "ANGRIP HER",
    "ping.defend": "FORSVAR HER",
    "ping.rally": "SAMLING PÅ MEG",
    "ping.need_escort": "TRENGER ESKORTE",
    "ping.escort_standard": "ESKORTER STANDARTEN",
    "ping.carrier_under_attack": "VOGNEN ER UNDER ANGREP",
    "ping.recovery_in_progress": "BERGING PÅGÅR",
    "ping.road_blocked": "VEIEN ER SPERRET",
    "ping.mines_detected": "MINER OPPDAGET",
    "ping.safe_route": "TRYGG RUTE MERKET",
    "ping.need_rescue": "TRENGER REDNING",
    "task.stop_thief": "STOPP TYVEN — standarten vår er på vandring",
    "task.secure_standard": "Sikre standarten vår — den ligger åpent",
    "task.escort_carrier": "Eskorter standartløpet hjem",
    "task.rescue": "Redd operatør {id} — en vogn kan plukke dem opp",
    "task.defend_relay": "Forsvar relé {id} — flagget er på vei ned",
    "task.repair_site": "Gjenoppbygg relé {id} — en lastebil med materiell fikser det",
    "task.recover": "Berg enhet {id} — tau den hjem",
    "task.towing_now": "Tauer enhet {id} — kjør hjem",
    "banner.down_wait": "DU ER NEDE — redeploy om {s}s",
    "banner.down_ready": "REDEPLOY NÅ (R) — eller kryp til en vogn",
    "banner.tow": "TAU ENHET {id} (T)",
    "label.you_down": "DU ER NEDE — R FOR REDEPLOY",
    "label.board_here": "VOGN HER — B FOR Å GÅ OM BORD",
    "label.operator_down": "OPERATØR NEDE",
    "label.repairing": "REPARERER {s}s",
    "label.relay": "RELÉ — {who}",
    "label.relay_damaged": "SKADET — lastebil + materiell gjenoppbygger",
    "label.relay_raising": "HEISES {s}s",
    "label.relay_dropping": "SENKES {s}s — FORSVAR!",
    "label.who_yours": "DERES",
    "label.who_enemy": "FIENDENS",
    "label.who_neutral": "NØYTRALT",
    "label.std_yours": "DIN STANDART",
    "label.std_enemy": "FIENDENS STANDART — STJEL DEN",
    "label.std_yours_down": "STANDARTEN DIN ER NEDE",
    "label.std_enemy_open": "FIENDENS STANDART LIGGER ÅPENT",
    "label.std_returns": "returnerer selv om {s}s",
    "ui.direct_on": "DIREKTE KJØRING — W/S gass, A/D sving, G avslutter",
    "ui.direct_off": "Direkte kjøring av — klikk-og-kjør tilbake.",
    "ui.spectating": "Tilskuer — du ser alt, du rører ingenting.",
    "ui.new_war": "En ny krig har begynt!",
    "ui.crewing": "Du bemanner enhet {id} — klikk på bakken for å kjøre",
  },
};

let LOCALE = "en";

export function setLocale(locale) {
  if (CATALOGS[locale]) LOCALE = locale;
  return LOCALE;
}

export function getLocale() {
  return LOCALE;
}

export function hasKey(key) {
  return key in CATALOGS.en;
}

export function t(key, params = null) {
  const text = CATALOGS[LOCALE][key] ?? CATALOGS.en[key] ?? key;
  if (!params) return text;
  return text.replace(/\{(\w+)\}/g, (m, k) => (k in params ? String(params[k]) : m));
}
